### ISSUE TITLE
谁在用 thrio？

### ISSUE THREAD

**Issue by foxsofter** [flutter-thrio/flutter_thrio#1]
欢迎留言写下使用 thrio 的情况，这也是对 thrio 的支持。

**Comment by kelciej** [comment]
正在调研，支持大神

**Comment by josercc** [comment]
从目前项目分离出来混合架构用了Thrio 公司后面项目都会用这个混合架构做

**Comment by hw20101101** [comment]
刚刚才发现 thrio，准备入门了 👍🏻

**Comment by shingohu** [comment]
使用中,非常👍🏻,墙裂推荐,有问题加群,群主解决问题非常及时
