### ISSUE TITLE
ios 无法跳转到flutter端 一直转圈 显示 hot restart

### ISSUE THREAD

**Issue by SnailLife** [flutter-thrio/flutter_thrio#11]
**Describe the bug**
example 下载下来在xcode运行 一直显示转圈

**To Reproduce**
在xcode真机14.3运行 无法正常显示页面

**Expected behavior**
控制台没有报错

**Flutter Doctor**
no issure

**OS & Device**
 - Device: iPhoneXR
 - OS: ios 14.3
 - flutter 2.0.1

**Error logs**
无 error log

**Comment by foxsofter** [comment]
可能是姿势问题，这个页面是过渡页，hot restart 的时候需要点击下，混合栈下的 hot restart 默认回到第一个 Flutter 页面

**Comment by SnailLife** [comment]
额可是我是直接down下来的 不是我自己写的工程





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: foxsofter <notifications@github.com&gt;
发送时间: 2021年3月8日 18:08
收件人: flutter-thrio/flutter_thrio <flutter_thrio@noreply.github.com&gt;
抄送: MrYang <359447505@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[flutter-thrio/flutter_thrio] ios 无法跳转到flutter端 一直转圈 显示 hot restart (#11)

**Comment by docee** [comment]
thrio在flutter 2.x上有问题，路由无法跳转。

**Comment by SnailLife** [comment]
👌 我切回去看下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Docee Huang <notifications@github.com&gt;
发送时间: 2021年3月8日 18:12
收件人: flutter-thrio/flutter_thrio <flutter_thrio@noreply.github.com&gt;
抄送: MrYang <359447505@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[flutter-thrio/flutter_thrio] ios 无法跳转到flutter端 一直转圈 显示 hot restart (#11)

**Comment by foxsofter** [comment]
老铁。。。吓到我了。。。 1.22.x 可以跑

**Comment by docee** [comment]
不过最好还是可以适配下2.x，大家一起搞搞？

**Comment by foxsofter** [comment]
欢迎欢迎，我暂时还没时间

**Comment by docee** [comment]
https://github.com/flutter-thrio/flutter_thrio/blob/74aa6fed70b9eb174a834b10c867ba62729fe284/lib/src/module/module_anchor.dart#L147

看起来应该是这个地方的问题，在Flutter 2.x SDK上，这里所有的泛型判断都是false。

**Comment by docee** [comment]
@foxsofter 已提交MR。
