### ISSUE TITLE
修改 demo 中的 biz1 和 flutter1 目录之后运行异常

### ISSUE THREAD

**Issue by hw20101101** [flutter-thrio/flutter_thrio#17]
想改个跟项目功能模块对应的名称，结果改了名称之后（已修改项目中所有的 biz1 和 flutter1），运行项目时卡在 hot restart 启动界面，点击 hot restart 无响应。

```
mac os 10.15.7
vs code  1.54.3
Xcode 12
iOS 14.4 模拟器
```

**Comment by foxsofter** [comment]
还要改对应的 key，另外建议你好好理解下模块的定义，再下手接入，注意，一个模块可以有多个子模块，但只能有一个页面
