### ISSUE TITLE
hello，请问应该怎样设置这个 thrio 项目的  launch image 呢？

### ISSUE THREAD

**Issue by hw20101101** [flutter-thrio/flutter_thrio#19]
我在 iOS 原生中设置了 launch image，但是 App 启动的时候  launch image 一闪而过，然后会显示几秒钟的空白界面。

请问怎样才能将这几秒钟的空白界面替换为  launch image 呢？

我照着一些网上的教程试了，无效， demo 链接：https://github.com/hw20101101/thrio_demo

谢谢！！

**Comment by foxsofter** [comment]
你试的是纯 Flutter 的方式吧，home 页面也是一闪而过的，目前不支持停留

**Comment by hw20101101** [comment]
就是这个 flutter_thrio 啊，那个几秒钟的空白界面不能替换为图片或显示转圈圈吗？不然体验太差。

**Comment by foxsofter** [comment]
你先确认下，几秒钟怎么来的吧

**Comment by hw20101101** [comment]
我通过日志看到，那几秒钟的空白就是 main() 函数到

ThrioModule 的

```
  @protected
  Future onModuleLoading(ModuleContext moduleContext) async {
    verbose('onModuleLoading: $key');
  }
``` 

之间的间隙，但是我不知道这里该怎么修改，还请点拨一下，谢谢！！  😄
