### ISSUE TITLE
hello，创建 swift 版的 ios 项目时遇到问题

### ISSUE THREAD

**Issue by hw20101101** [flutter-thrio/flutter_thrio#22]
我在 example 目录下使用 ` flutter create -i swift . ` 重新创建 ios 项目之后，AppDelegate 中的代码是否可以转为 swift 版？

```
 
    [ThrioModule init:[MainModule new]];

    UINavigationController *nvc = [[NavigatorNavigationController alloc] initWithUrl:@"/biz1/flutter1" params:nil];
    self.window.rootViewController = nvc;
    [self.window makeKeyAndVisible];

```

如果可以转 swift，那应该怎样转呢？谢谢！！

**Comment by hw20101101** [comment]
一些第三方 SDK 在 OC 项目中报错，如下：

<img width="1192" alt="WX20210512-224820@2x" src="https://user-images.githubusercontent.com/9107226/118075621-f8052680-b3e2-11eb-8092-5aed6f829cac.png">

根据反馈得到的解决办法就是使用 swift 来创建 ios 项目。

**Comment by foxsofter** [comment]
这个不用问吧，就是一个如何在 Swift 项目中引用 objc 代码

**Comment by hw20101101** [comment]
转到 swift 之后报错 `No such module 'thrio' `


![WX20210513-195708@2x](https://user-images.githubusercontent.com/9107226/118123655-260c5a00-b427-11eb-9875-adc63ce4286e.jpg)


<img width="982" alt="WX20210513-201050@2x" src="https://user-images.githubusercontent.com/9107226/118124665-7d5efa00-b428-11eb-8f52-c2cbc92c0b54.png">

**Comment by hw20101101** [comment]
转到 swift 之后报错 `No such module 'thrio' `


![WX20210513-195708@2x](https://user-images.githubusercontent.com/9107226/118123655-260c5a00-b427-11eb-9875-adc63ce4286e.jpg)


<img width="982" alt="WX20210513-201050@2x" src="https://user-images.githubusercontent.com/9107226/118124665-7d5efa00-b428-11eb-8f52-c2cbc92c0b54.png">

**Comment by hw20101101** [comment]
转到 swift 之后报错 `No such module 'thrio' `


![WX20210513-195708@2x](https://user-images.githubusercontent.com/9107226/118123655-260c5a00-b427-11eb-9875-adc63ce4286e.jpg)


<img width="982" alt="WX20210513-201050@2x" src="https://user-images.githubusercontent.com/9107226/118124665-7d5efa00-b428-11eb-8f52-c2cbc92c0b54.png">

**Comment by foxsofter** [comment]
[importing_objective-c_into_swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)
[importing_swift_into_objective-c](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c)

**Comment by hw20101101** [comment]
@foxsofter   thanks，还差最后一步。

ThrioModule 和 MainModule 初始化报错：

<img width="1101" alt="WX20210514-144231@2x" src="https://user-images.githubusercontent.com/9107226/118232218-d4191200-b4c2-11eb-8ad5-61e619d3030e.png">

**Comment by foxsofter** [comment]
你应该调 init 方法

**Comment by hw20101101** [comment]
init 也报这个错误

**Comment by foxsofter** [comment]
不是同一个 init 方法 ~_~

**Comment by hw20101101** [comment]
@foxsofter   那是什么？能不能举个例子？

**Comment by foxsofter** [comment]
![image](https://user-images.githubusercontent.com/1644853/118390979-8cca8700-b664-11eb-85e0-c790d7ea879f.png)

**Comment by hw20101101** [comment]
@foxsofter  感谢！

**Comment by hw20101101** [comment]
@foxsofter  感谢！

终于可以了，从未接触过这种写法。

` ThrioModule.`init`(MainModule()) `
