### ISSUE TITLE
cachedEngineId must not be null，是我使用方式有问题吗

### ISSUE THREAD

**Issue by jzllovecat** [flutter-thrio/flutter_thrio#26]
Android调ThrioNavigator.push("tab_0")到flutter的activity必须继承ThrioActivity？否则没反应
ThrioActivity extends Activity，为啥不继承AppCompatActivity 如果这样好多地方不能直接使用了
间接跳转ThrioActivity后再push正常
把老项目的activity继承ThrioActivity后onCreate（）里push时还有崩溃，是我集成方式不对吗，ThrioModule.init(new ThrioModule(),this,true);我只加了这一句然后就调用了push方法
![企业微信截图_16213319187616](https://user-images.githubusercontent.com/19180995/118636881-be2f8800-b807-11eb-974d-3e7c10fca2e1.png)

**Comment by foxsofter** [comment]
1. 不要开启多引擎，前提是你知道要干什么
2. 这个继承关系是由 Flutter SDK 决定的
