### ISSUE TITLE
支持FlutterView级别的使用方式

### ISSUE THREAD

**Issue by icespring** [flutter-thrio/flutter_thrio#28]
粗略的看了下代码，貌似thrio目前默认的路由模式是单引擎单Navigator的模式，我目前有这样一个需求，Android和iOS的主页面都是有TabBar的，并且TabBar的4个TabView中，两个是FlutterView，另外两个目前只能保持Native实现，如何满足这类的需求？

**Comment by foxsofter** [comment]
FlutterEngineGroup 上这个，tab 里面放官方的 FlutterView

**Comment by icespring** [comment]
> FlutterEngineGroup 上这个，tab 里面放官方的 FlutterView

但是FlutterEngineGroup并不支持内存共享，想共享状态的话只能通过Native，比较麻烦

**Comment by foxsofter** [comment]
至少能实现，通过thrio来传递状态就好了，本来就提倡页面级状态

**Comment by foxsofter** [comment]
#29
