### ISSUE TITLE
flutter侧白屏 Failed to create platform view rendering surface

### ISSUE THREAD

**Issue by wanghao522** [flutter-thrio/flutter_thrio#34]
**Describe the bug**
platform_view.cc(81):Failed to create platform view rendering surface
swift 项目，native侧 跳转flutter，跳转过去后，界面渲染不出来（白屏），点击界面，上面的按钮可以正常显示，flutter监视器 上可以正常看到按钮大小位置（swift项目，你们demo项目正常，对比了代码木有找到原因，flutter侧代码完全用demo里面的，猜测是native侧的问题）

**Expected behavior**

**Flutter Doctor**

**OS & Device**
 - Device:   真机，模拟器
 - OS: ios14 
 - Version：2.0.11
 - flutter ver：2.2.3
 - swift ：5.3

**Error logs**
platform_view.cc(81):Failed to create platform view rendering surface

**Comment by foxsofter** [comment]
方便的话把你的 native 代码贴上来

**Comment by wanghao522** [comment]
[hyyy.zip](https://github.com/flutter-thrio/flutter_thrio/files/7044473/hyyy.zip)
![image](https://user-images.githubusercontent.com/6700434/130743348-eed0a3b8-3bb0-4fc5-a1a1-799f0b229f3b.png)
运行这个宿主项目哈 感谢

**Comment by foxsofter** [comment]
flutter 端的代码呢，这个确实没办法看出来什么，还有接入的方式有点奇怪啊，可能需要先确认下你的编译方式是否正常

**Comment by wanghao522** [comment]
> flutter 端的代码呢，这个确实没办法看出来什么，还有接入的方式有点奇怪啊，可能需要先确认下你的编译方式是否正常
代码在里面的
![image](https://user-images.githubusercontent.com/6700434/130773539-e72dee71-d186-44e1-833a-608772817f04.png)
先执行 cd fluttermodule flutter pub get 然后 cd .. pod install，正规项目接入都是这样的，podfile里面就是这样写的，跟你们demo里面 podflie写法不一样，我接入flutter就是这样弄的（没有接入flutter_thrio时候自己在appdelegate里面初始化flutter engine ，用method_channel 跳转都是好用的，按照你的demo接入后flutter页面渲染不出来）

**Comment by foxsofter** [comment]
你把原生那块的写法改成跟 demo 一样的先试试吧

**Comment by foxsofter** [comment]
这依赖内部源吧，确实没跑起来，Swift的例子我demo 也有，你自己调试看看吧，先关闭了
