### ISSUE TITLE
Flutter2.5.2版本中，AndroidKeyProcessor类已经删除

### ISSUE THREAD

**Issue by qa137** [flutter-thrio/flutter_thrio#35]
升级到Flutter2.5.2后，程序无法进行编译，报错找不到AndroidKeyProcessor类

**Comment by foxsofter** [comment]
这个版本的 Flutter 还没适配，最近会发新版解决

**Comment by qa137** [comment]
手贱已升级，尝试修改源码，但键盘事件还是有些小问题，坐等更新了

**Comment by foxsofter** [comment]
先别升级吧，我还没时间来解决，不只是这个问题，还会有其它问题

**Comment by liujinlong123** [comment]
[https://github.com/flutter/engine/pull/25628/commits/d4b9518bd1ef017812ac057ef4e397c954da41f9](url)

暂时修改AndroidKeyProcessor为KeyboardManager，可以编译通过；期待thrio更新

**Comment by foxsofter** [comment]
参考 main_nullsafety 分支是否解决你的问题。
