### ISSUE TITLE
pop 手势与系统冲突, H5页面无法选择相册照片

### ISSUE THREAD

**Issue by Janyau** [flutter-thrio/flutter_thrio#41]
**Describe the bug**
pop 手势与系统冲突, H5页面无法选择相册照片

**To Reproduce**
点击"选择照片" -> 多选(Choose Files) -> Photo Library -> 选择照片 -> 添加

**Install**
依次在终端执行如下命令安装依赖
1. cd my_flutter
2. flutter pub get
3. flutter build ios
4. cd flutter_webview
5. pod install

**Expected behavior**
去掉 UINavigationController+PopGesture.m 文件里的手势就正常了

![image](https://user-images.githubusercontent.com/14040182/142608241-47d80069-1ead-4466-87f5-9f19ce5864e8.png)

**Flutter Doctor**
[✓] Flutter (Channel master, 2.0.3, on macOS 11.5.1 20G80 darwin-x64, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

**OS & Device**
 - Device: iPhone6s
 - OS: iOS14.7.1
 
[flutter_webview.zip](https://github.com/flutter-thrio/flutter_thrio/files/7569863/flutter_webview.zip)

**Comment by foxsofter** [comment]
这个做下排除才行，主要是根据类名来做
