### ISSUE TITLE
通过 flutter build ios-framework 生成的 framework 拖入项目中的集成方式 

### ISSUE THREAD

**Issue by yqhyam** [flutter-thrio/flutter_thrio#46]
ThrioNavigator pushUrl 跳转没响应。
setFlutterPageBuilder 回调也不走。
请问是使用方式有问题吗？

**Comment by foxsofter** [comment]
你先用 flutter module 调试好，再以这种方式编译集成

**Comment by yqhyam** [comment]
> 你先用 flutter module 调试好，再以这种方式编译集成

flutter engine 直接调用可以跳转能到对应页面
