### ISSUE TITLE
 如何设置多引擎

### ISSUE THREAD

**Issue by kelciej** [flutter-thrio/flutter_thrio#5]
**Describe the bug**
想要看看多引擎如何实现
打开 MainApp 中 您注释掉的句子  ThrioModule.init( MainModule, this, true)。
但是报错，找不到engindId

**To Reproduce**

> ThrioModule.init( MainModule, this, true)

**Flutter Doctor**
Flutter 1.22.4

**OS & Device**
Android 10
**Error logs**

> E/AndroidRuntime(11476): FATAL EXCEPTION: main
E/AndroidRuntime(11476): Process: com.hellobike.thrio_example, PID: 11476
E/AndroidRuntime(11476): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hellobike.thrio_example/io.flutter.embedding.android.ThrioActivity}: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: 'biz1'

**Comment by kelciej** [comment]
您好，请教下 isNested具体什么意思？谢谢

**Comment by foxsofter** [comment]
多引擎不支持 ThrioActivity 作为 启动 Activity，因为多引擎默认是懒加载的

**Comment by foxsofter** [comment]
> 您好，请教下 isNested具体什么意思？谢谢

这个只是用来完善一些内部逻辑，表示当前是不是内嵌的页面
