### ISSUE TITLE
从FlutterA页面跳转进入原生B页面，再跳转进入FlutterC页面，会导致FlutterC页面渲染不出来

### ISSUE THREAD

**Issue by YinHAHA** [flutter-thrio/flutter_thrio#50]
从FlutterA页面跳转进入原生B页面，再跳转进入FlutterC页面，会导致FlutterC页面渲染不出来，看数据是做了接口请求，并返回数据了，但是FlutterC页面却没有渲染出来，此时切换到后台，再切到前台，数据能正常显示出来了

**Comment by foxsofter** [comment]
thrio 本身不做接口请求，另外你这个是哪个版本或分支上的问题标注下

**Comment by YinHAHA** [comment]
> thrio 本身不做接口请求，另外你这个是哪个版本或分支上的问题标注下

 用的版本是：2.0.11，我自己做的接口请求，问题点是：有数据没有渲染出来，切到后台再回到前台就能正常显示了。。。

**Comment by foxsofter** [comment]
这个估计跟 thrio 应该是没啥关系的
