### ISSUE TITLE
重复注册会导致crash

### ISSUE THREAD

**Issue by wangjunli0607** [flutter-thrio/flutter_thrio#56]
1、能否提供一个方法来表示ThrioModule init完成

**Comment by foxsofter** [comment]
> 1、能否提供一个方法来表示ThrioModule init完成

有回调的

**Comment by foxsofter** [comment]
> 2、能否提供一个方法来判断当前ThrioModule是否已经被注册

重复注册会抛异常

**Comment by foxsofter** [comment]
就是不能重复注册啊，重复了就完犊子了
