### ISSUE TITLE
原生页面返回 flutter 页面，参数传不过来

### ISSUE THREAD

**Issue by huforrest** [flutter-thrio/flutter_thrio#59]
![B0EDA0393B3AE888E63855240A4C5659](https://github.com/user-attachments/assets/8c8cfb51-614c-4041-ab07-f3a323a50a3a)
demo 跑起来之后，如图所示，页面1是 flutter 页面，页面2是原生页面，从页面2返回页面1时，页面1无法接收到页面2返回来的数据。

**Comment by foxsofter** [comment]
pub 4.16.1 解决了
