### ISSUE TITLE
android example跑不起来

### ISSUE THREAD

**Issue by Yahiko7** [flutter-thrio/flutter_thrio#6]
如图所示
![image](https://user-images.githubusercontent.com/15901380/109599907-12a35f80-7b57-11eb-8fdd-74c575cf5ad0.png)

报错信息：
Could not determine the dependencies of task ':thrio:compileDebugKotlin'.
> Could not resolve all files for configuration ':thrio:debugRuntimeClasspath'.
   > Could not find io.flutter:flutter_embedding_debug:1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed/flutter_embedding_debug-1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed.pom
       - https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed/flutter_embedding_debug-1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed.pom
       - https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed/flutter_embedding_debug-1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed.pom
     Required by:
         project :thrio

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by kelciej** [comment]
flutter相关的依赖拉不下来。
android/build.gralde配置


` buildscript {
    ext.kotlin_version = 你的版本
    repositories {
        google()
        jcenter()
        maven {
            url "https://storage.googleapis.com/download.flutter.io"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:你的版本'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.8'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://storage.googleapis.com/download.flutter.io"
        }
    }
}`

**Comment by foxsofter** [comment]
应该是Flutter SDK版本不匹配了
