### ISSUE TITLE
thrio 维护公告

### ISSUE THREAD

**Issue by foxsofter** [flutter-thrio/flutter_thrio#8]
**2.1.x版本之后，不再维护 not nullsafety 分支，如可能还是尽快升级到 nullsafety 吧**

本项目 API 已经稳定，不太可能出现 break change，当前稳定版本 2.0. x，当 x 是偶数时表示支持 Flutter 2.0 不带 nullsafety，当 x 是奇数时表示支持 Flutter 2.0 带 nullsafety。

thrio 是个人项目，目前是我一人在维护，[原仓库](https://github.com/hellobike/flutter_thrio)不再更新。

最近遇到被问到与其它开源库对比的比较尖锐的一些问题，有时候我是不太想回答的，说多了有拆台嫌疑。

可以理解，很多人还是想得到更多信息来判断是否应不应该使用 thrio，我的几条建议如下：

1. 看自己的需求，满足自己需求是前提
2. 看代码质量，这是最主要的一点
3. 自己多测测，可以的话看看稳定性如何
4. 可参考下 issue 数量和 star 数量比，未解决 issue 数量等
5. 看代码更新频次 

最后还是说一句：thrio 是目前唯一支持 Flutter 混合栈跨栈路由的开源库，这句话从 thrio 开源至今一直都是有效的，等将来出现具备Flutter 混合栈跨栈路由的开源库，我再来改掉。

跨栈路由：无需关注页面类型是 iOS、Android 还是 Flutter，都一样具备完整的路由能力，调用者打开一个页面，接收该页面的回调，接收该页面的页面通知，即使将来其页面类型变更也无所谓。

**Comment by foxsofter** [comment]
## 1.8.0

* feat: 添加 `iOS` 和 `Android` 的 `ModuleContext`，并默认传递给 `Flutter`
* feat: 完善 `shouldCanPop`，支持混合栈用于判断是否显示箭头
* fix: 修复 `ThrioActivity` 作为 lanuch Activity 时可能导致出现加载页的bug
* feat: `ModuleContext` 支持 `Stream` 接口

## 1.8.1

* feat: 增加 `lastFlutterRoute` 和 `allFlutterRoutes` 两个 接口
* fix: `lastRoute` 返回空不是 `null`

## 1.8.2

* feat: 移除 kotlin-android-extensions
* feat: 适配 Flutter 2.x.x 版本，可尝试在此版本上使用，建议等待 nullsafety 版本更稳妥

**Comment by foxsofter** [comment]
## 1.8.4

* fix: 优化 dart 代码
* fix: 修复部分使用场景下的 bug

**Comment by plokmju88** [comment]
QQ 群已经加满了，开新群了吗？还是我要怎么入群？

**Comment by foxsofter** [comment]
群人数已提升，随便加

**Comment by foxsofter** [comment]
## 2.0.1

* fix: moduleContext.on 无法收到原生的状态

## 2.0.1-nullsafety

* fix: moduleContext.on 无法收到原生的状态

**Comment by foxsofter** [comment]
## 1.8.5 （Flutter 1.x）

* fix: 原生页面 pop 某些场景下可能将 Flutter 页面也 pop

## 2.0.2 （Flutter 2.x）

* fix: 原生页面 pop 某些场景下可能将 Flutter 页面也 pop

## 2.0.2-nullsafety （Flutter 2.x with nullsafety）

* fix: 原生页面 pop 某些场景下可能将 Flutter 页面也 pop
