### ISSUE TITLE
android example报错

### ISSUE THREAD

**Issue by Yahiko7** [flutter-thrio/flutter_thrio#9]
如图，android example报错
![image](https://user-images.githubusercontent.com/15901380/109679709-cbe55200-7bb6-11eb-8162-223967fabe4d.png)
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (9, 8): Unresolved reference: kotlinx
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (14, 9): Unresolved reference: tv_native
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (14, 19): Variable expected
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (16, 9): Unresolved reference: btn_10
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (34, 9): Unresolved reference: btn_11
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (40, 9): Unresolved reference: btn_12
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (52, 9): Unresolved reference: btn_13
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (58, 9): Unresolved reference: btn_20
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (71, 9): Unresolved reference: btn_21
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (75, 9): Unresolved reference: btn_22
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (88, 9): Unresolved reference: btn_23
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (92, 9): Unresolved reference: btn_3
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (113, 17): Unresolved reference: tv_native
e: /Users/zhebian/Desktop/testCode/flutter_thrio/example/android/app/src/main/kotlin/com/hellobike/thrio_example/Native1Activity.kt: (113, 27): Variable expected

**Comment by foxsofter** [comment]
自己先看看环境缺了啥吧

**Comment by Yahiko7** [comment]
解决了，谢谢大佬
